### ISSUE TITLE
Implement a cool Rooms page

### ISSUE THREAD

**Issue by fabianome** [juliemar/matrix#52]
Protótipo:
https://www.figma.com/proto/RGLv1bHeE58wO0qXGxAxv0h0/Matrix-Layouts?node-id=1%3A4&viewport=450%2C473%2C0.5&scaling=min-zoom

![Matrix Rooms](https://user-images.githubusercontent.com/5340919/55509571-a51cea80-5632-11e9-8fd7-67f9dc52b471.png)

**Comment by lgiacomini92** [comment]
Closed by #69
